version: '3.3'

services:
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodb: